on:
  label:
    types: [created]

jobs:
  check_labels:
    runs-on: ubuntu-18.04
    steps:
    - name: getting label
      id: label
      if: contains(github.event.pull_request.labels.*.name, 'e2e_google')
      uses: klaudioz/testing_github_actions@master
      with:
        function-name: 'e2e'
        cloud-name: 'google'
